apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: live
  name: terraform-executor
rules:
  - apiGroups: [""]
    resources: ["pods", "replicasets", "deployments", "services", "configmaps"]
    verbs: ["get", "watch", "list", "post", "patch", "delete", "create"]
