apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: execute-terraform
  namespace: live
subjects:
  - kind: ServiceAccount
    name: terraformer
    namespace: live
roleRef:
  kind: Role
  name: terraform-executor
  apiGroup: rbac.authorization.k8s.io
