apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-agencyliveapi-binding
  namespace: live
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: agencyapi
    namespace: live
  - kind: ServiceAccount
    name: agencyengagementboardsapi
    namespace: live
  - kind: ServiceAccount
    name: employerengagementboardsapi
    namespace: live
