variable "storage_account_name" {}
variable "container_name" {}
variable "key" {}
variable "az_storage_access_key" {}
variable "jwks_uri" {}
variable "jwks_audience" {}
variable "jwks_issuer" {}
variable "jwks_algorithm" {}
variable "elastic_host" {}
variable "elastic_port" {}
variable "elasticsearch_auth_file" {}
variable "appinsights_instrumentation_key" {}
variable "k8s_host" {}
variable "sa_ca_crt" {}
variable "sa_jwt_token" {}